name: feature_discovery
description: >-
  A Flutter package that implements Material Design Feature discovery
  to show a description of specific features to new users.
  See https://tinyurl.com/FeatureDiscovery
version: 0.15.0
homepage: https://github.com/ayalma/feature_discovery

environment:
  # This should match the Flutter stable SDK constraint.
  # See https://github.com/flutter/flutter/blob/stable/packages/flutter/pubspec.yaml.
  sdk: ^3.13.0
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.2.0

  provider: ^6.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
